### ISSUE TITLE
add vimeo playlist for full episodes

### ISSUE THREAD

**Issue by astratagem** [templesmc/tuupdate#37]
Will probably need a plugin that will handle this.

**Comment by bpizzle** [comment]
https://vimeo.com/album/1521800

**Comment by astratagem** [comment]
http://wordpress.org/plugins/vimeo-channel-gallery/

**Comment by astratagem** [comment]
Installed [Vimeography](http://vimeography.com/) plugin. Playlist is still not working. Test to see whether it conflicts with other plugins, esp. Vimeo hotfix.

**Comment by astratagem** [comment]
The network-activated [Vimeo oembed hotfix](https://gist.github.com/samargulies/1284826) broke this plugin. We deactivated it because it didn't appear functional.
