### ISSUE TITLE
vimeo playlist has ceased working

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#38]
http://templeupdate.com/archives/
simply says "[vimeography id="1"]"

**Comment by astratagem** [comment]
It's possible that the plugin was deactivated.

But on Friday, even when the plugin was active, no more than one video was
showing... I might have to open a support ticket with the developer.

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.

**Comment by astratagem** [comment]
Plugin was deleted mysteriously. Re-installed.
