### ISSUE TITLE
everything on footer excluding the search bar is missing on IE

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#39]
Students cannot find the log in button using Internet Explorer. This is only a problem because some classroom computers only have IE installed.

**Comment by astratagem** [comment]
Strange. I'll look into this tonight.

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.
