### ISSUE TITLE
about page still isn't clickable?

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#41]

**Comment by astratagem** [comment]
Did we discuss just having another link in the submenu?

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.

**Comment by bpizzle** [comment]
I don't remember now what we decided, but I feel like that wasn't the solution. 
I'm having a weird idea right now that I don't really know if I like but I'm going to right it down before I forget it.

What is "about" was another category and we could have posts under it--plain "about" which will have the content that the about pg has right now, a site credits post, and a staff list post. So it will look like 3 different sections on one page but really it will be a category with posts? I haven't really thought this through but maybe it could work.

**Comment by astratagem** [comment]
That could work but I'd have to make a slightly different template for that category in particular so it wouldn't have all the information about the author, date, categories, etc.

**Comment by bpizzle** [comment]
right, but before you do anything let me sleep on this. i dunno if it's actually a good idea or if it's stupid as fuck.

**Comment by bpizzle** [comment]
i mean another thing is just to list the site credits on the about page as a link, so if you're on a mobile device you'll just have to go to the about page first, then see the site credits. but if you're on a computer you'll be able to see the dropdown fine. which is I think what I thought was the best idea before.

**Comment by astratagem** [comment]
You're right, that's the one.

On Tuesday, October 15, 2013, bpizzle wrote:

> i mean another thing is just to list the site credits on the about page as
> a link, so if you're on a mobile device you'll just have to go to the about
> page first, then see the site credits. but if you're on a computer you'll
> be able to see the dropdown fine. which is I think what I thought was the
> best idea before.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/montchr/tuupdate/issues/41#issuecomment-26363375
> .

## 

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.
