### ISSUE TITLE
content should not be written in caps.

### ISSUE THREAD

**Issue by astratagem** [templesmc/tuupdate#43]
Students should be made aware of this. 

http://templeupdate.com/new-garage-adds-parking-options/

**Comment by bpizzle** [comment]
this was just an example post. Peter copied and pasted a regular script that the kids are used to seeing, just to show them quickly what they have to do. he told them not to use all caps cos he's not a dumb-dumb.

**Comment by astratagem** [comment]
Sorry! That's good.
