### ISSUE TITLE
I don't like this goddamn red border!!!!!!!!!

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#48]
http://templeupdate.com/new-south-philly-favorite-in-morgan-hall/
also can we make the caption text smaller? it should be smaller :D

**Comment by bpizzle** [comment]
i meant the border around the image.

**Comment by astratagem** [comment]
fixed in https://github.com/montchr/exai.css/commit/1c188c7f730f5b3153a06dbf1670079cba05bc0b
