### ISSUE TITLE
forecast widget breaks every day between 18:00 and 19:00 EST

### ISSUE THREAD

**Issue by astratagem** [templesmc/tuupdate#53]
I have only seen this today, but I believe it must happen every day.

We use this code to calculate the temperature change:

``` php
// Get hourly conditions
$hourly = $forecast->getForecastToday($latitude, $longitude);

...

// Hourly conditions variables
$hour_now           = $hourly[0];
$hour_next          = $hourly[1];
$hour_now_temp      = round($hour_now->getTemperature());
$hour_next_temp     = round($hour_next->getTemperature());
// Temperature change direction
$temp_dir           = $hour_now_temp < $hour_next_temp ? 'rising' : 'falling';
```

This assumes that there actually is a next hour in the JSON API response. But if it's the last hour of the day (23:00 to 23:59 UTC or 18:00 to 18:59 EST), there is no next hour, so there is nothing in the `$hourly` array at `[1]`, only `[0]`. This causes a fatal PHP error, thus breaking everything and ruining everyone's evenings.

The reason that it stops there and doesn't keep going is because `getForecastToday()` does what it says – it only gets today, so anything in the last hour of the day will theoretically break.

_This would of course be slightly less of an issue if we corrected the timezone difference_, so that instead of breaking in the evening, it breaks between 23:00 and 23:59 EST.

So I need to come up with a workaround for this particular timespan, when `$hour_next` is undefined. The less hackish, the better.

**Comment by astratagem** [comment]
@loafintree This is a weird bug. Any thoughts?

**Comment by astratagem** [comment]
Looking more into it, this is likely an issue with [the Forecast.io PHP wrapper](https://github.com/tobias-redmann/forecast.io-php-api).

``` php
  /**
   * Will return conditions on hourly basis for today
   *
   * @param type $latitude
   * @param type $longitude
   * @return \ForecastIOConditions|boolean
   */
  function getForecastToday($latitude, $longitude) {

    $data = $this->requestData($latitude, $longitude);

    if ($data !== false) {

      $conditions = array();

      $today = date('Y-m-d');

      foreach ($data->hourly->data as $raw_data) {

        if (date('Y-m-d', $raw_data->time) == $today) {

          $conditions[] = new ForecastIOConditions($raw_data);

        }

      }

      return $conditions;

    } else {

      return false;

    }

  }
```

**Comment by loafintree** [comment]
Can you use a conditional statement for if hour_now =  the last hour of the day, reset clock.

**Comment by astratagem** [comment]
@loafintree I'll look into that. Thanks for the suggestion.

[Looks like](http://stackoverflow.com/questions/10197900/given-a-unix-timestamp-how-to-get-beginning-and-end-of-that-day) I could use `strtotime()` to get there...

**Comment by astratagem** [comment]
Set an alarm for 18:00 and test out the patch on the `forecast-last-hour` branch.
