### ISSUE TITLE
Advanced Excerpt is showing "View More" link twice

### ISSUE THREAD

**Issue by bpizzle** [templesmc/tuupdate#64]
The whole network is really buggy right now due to WPEngine, so this may be related. However, it could have something to do with your fix that got it to strip br's from the excerpt.

**Comment by astratagem** [comment]
:confounded:

**Comment by astratagem** [comment]
Did this just start happening?

**Comment by bpizzle** [comment]
I don't know, I think so. I swear I looked at it Tuesday and this wasn't
happening.

On Thu, Apr 24, 2014 at 2:04 PM, Chris Montgomery
notifications@github.comwrote:

> Did this just start happening?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/templesmc/tuupdate/issues/64#issuecomment-41312531
> .

## 

Bella Alba Pezzati

_TUTV Web Manager & Social Media Coordinator_
Annenberg Hall Rm 1J
2020 N. 13th Street
Philadelphia, PA 19122

bella@temple.edu
_mobile_ (267) 721-3188
_office_ (215) 204-2092
_fax_ (215) 204-7097

**Comment by astratagem** [comment]
> I don't know, I think so. I swear I looked at it Tuesday and this wasn't
> happening.

cc: @loafintree

**Comment by astratagem** [comment]
@bpizzle All this needs is an update to the new Advanced Excerpt plugin in development, as discussed in templesmc/tutv/issues/68

https://github.com/deliciousbrains/wp-advanced-excerpt

**Comment by astratagem** [comment]
From 2952e75's commit message:

> The new Advanced Excerpt plugin is behaving unpredictably. Our best
> option for Temple Update is to completely disable it for now and use the
> basic WP excerpt.
> 
> Initially used to override Advanced Excerpt's "read more" in
> 8aa6dc4.
