### ISSUE TITLE
undefined var `$id` in `tuu_get_the_slug()`

### ISSUE THREAD

**Issue by astratagem** [templesmc/tuupdate#67]
> PHP Notice: Undefined variable: id in /var/www/smcsites/htdocs/wp-content/themes/templeupdate/lib/custom.php on line 115

See https://github.com/templesmc/smc-themes/issues/136

**Comment by astratagem** [comment]
I think `basename(get_permalink());` can be used in more places to make this function simpler and to fix the errors.

**Comment by astratagem** [comment]
https://github.com/templesmc/tuupdate/blob/master/lib/custom.php#L93

**Comment by loafintree** [comment]
Why do we need to have a custom function to get the slug?

**Comment by astratagem** [comment]
Like I said, there's no need for the current complexity of this function. `basename(get_permalink());` should do just fine. AFAIK there is no core function to get the slug. This function can likely be re-written to simply return the results of `basename(get_permalink());`. But I don't recommend replacing the function with `basename(get_permalink());` – my rule of thumb is if you're calling a function as an argument to another function, then this should be abstracted to a single function e.g. `tuu_get_the_slug()`.

**Comment by loafintree** [comment]
That doesn't answer my question though. Why do we need it at all?

**Comment by astratagem** [comment]
Because `tuu_the_slug()` is used everywhere. That's a wrapper for `tuu_get_the_slug()` – instead of returning, it echoes.

https://github.com/templesmc/tuupdate/search?utf8=%E2%9C%93&q=tuu_the_slug&type=Code

**Comment by loafintree** [comment]
It's used in 5 files. The error appears to be a core problem. I've added a patch to wp-includes/class-wp-error.php
https://core.trac.wordpress.org/ticket/29583
