### ISSUE TITLE
hover link colors are wonky

### ISSUE THREAD

**Issue by astratagem** [templesmc/tuupdate#8]

**Comment by astratagem** [comment]
i think i fixed most of them. what do you think @bpizzle?

**Comment by bpizzle** [comment]
the social media buttons on the side (i.e., Follow @TempleUpdate) are all the same (no change in color on hover) except the sportsdesk one, which turns black.

**Comment by astratagem** [comment]
Good catch. Weird.

On Wednesday, September 25, 2013, bpizzle wrote:

> the social media buttons on the side (i.e., Follow @TempleUpdate) are all
> the same (no change in color on hover) except the sportsdesk one, which
> turns black.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/montchr/tuupdate/issues/8#issuecomment-25086052
> .

## 

---

_Chris Montgomery_
_This Storm Observatory_
stormobservatory.com
mont.chr@gmail.com

Web Editor
The Temple News
temple-news.com
web@temple-news.com

Web Developer
School of Media and Communication
Temple University
smc.temple.edu
montchr@temple.edu

_Sous les pavés, la plage_.
